fail_fast: true  # to stop running hooks after one fails
default_stages: [commit, push]

default_language_version:
    python: python3.9

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: check-docstring-first
    - id: check-json
    - id: check-merge-conflict
    - id: check-xml
    - id: check-yaml
    - id: debug-statements
    - id: double-quote-string-fixer
    - id: end-of-file-fixer
    - id: trailing-whitespace

  - repo: https://github.com/IamTheFij/docker-pre-commit
    rev: v2.0.1
    hooks:
      - id: docker-compose-check
        name: docker-compose-check

  - repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies: [
            'flake8-colors',
            'pep8-naming',
            'flake8-quotes',
            'flake8-comprehensions',
            'flake8-deprecated',
        ]
